"use client";

import React, { useCallback, useEffect, useMemo, useState } from "react";
import {
  Button,
  Card,
  Icon,
  ICONS,
  Badge,
  EmptyState,
  Skeleton,
  cx,
  FindingStatusBadge,
  ScoreRing,
  ResultBadge,
} from "@/components/ui";
import { PageHeader } from "@/components/shell";
import { useToast } from "@/components/toast";
import {
  Verification,
  Finding,
  formatDate,
  timeAgo,
  SEVERITY_LABEL,
} from "@/lib/types";

function extractScanIdFromHref() {
  return new URLSearchParams(window.location.search).get("id") ?? "";
}

export function ReportsClient() {
  const toast = useToast();
  const [verifications, setVerifications] = useState<Verification[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("all");
  const [selectedId, setSelectedId] = useState<string>(() => extractScanIdFromHref());
  const [detail, setDetail] = useState<{
    verification: Verification;
    findings: Finding[];
  } | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);

  const load = useCallback(() => {
    setLoading(true);
    fetch("/api/verifications")
      .then((r) => r.json())
      .then((d) => setVerifications(d.verifications ?? []))
      .catch(() => toast("error", "Failed to load reports"))
      .finally(() => setLoading(false));
  }, [toast]);

  useEffect(load, [load]);

  const loadDetail = useCallback((id: string) => {
    setDetailLoading(true);
    setDetail(null);
    fetch(`/api/verifications?id=${id}`)
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then((d) => setDetail(d))
      .catch(() => toast("error", "Failed to load report"))
      .finally(() => setDetailLoading(false));
  }, [toast]);

  useEffect(() => {
    if (selectedId) loadDetail(selectedId);
  }, [selectedId, loadDetail]);

  const filtered = useMemo(
    () =>
      verifications.filter(
        (v) => filter === "all" || v.result === filter,
      ),
    [verifications, filter],
  );

  const download = (v: Verification, findings: Finding[]) => {
    const lines: string[] = [
      "==============================================",
      "  LABELGUARD — INSPECTION REPORT",
      "  Legal Metrology Compliance Verification",
      "==============================================",
      "",
      `Report ID      : ${v.id}`,
      `Generated      : ${new Date(v.createdAt).toLocaleString("en-IN")}`,
      `Product        : ${v.productName}`,
      `Verdict        : ${v.result.toUpperCase()} (score ${v.score}/100)`,
      `Checks         : ${v.passed} pass · ${v.failed} fail · ${v.warnings} warning`,
      "",
      "SUMMARY",
      "-------",
      v.summary,
      "",
      "FINDINGS (rule-level evidence)",
      "-----------------------------",
    ];
    for (const f of findings) {
      lines.push(
        `[${f.status.toUpperCase().padEnd(14)}] ${f.code} — ${f.title}`,
        `    Status: ${f.detail}`,
        `    Evidence: ${f.evidence ?? "—"}`,
        `    Reference: ${f.legalReference}`,
        "",
      );
    }
    lines.push(
      "----------------------------------------------",
      "This report was generated by ScanSure using",
      "OCR-extracted label declarations. It serves as",
      "evidence for marketplace onboarding and statutory",
      "inspection under LM (Packing Rules) 2011.",
    );
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `scansure-report-${v.id.slice(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast("success", "Report downloaded");
  };

  return (
    <>
      <PageHeader
        title="Inspection Reports"
        subtitle="Evidence-backed verification reports, ready for marketplace upload"
      />

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-5">
        {/* List */}
        <Card className="lg:col-span-2">
          <div className="flex items-center gap-2 border-b border-ink-100 px-4 py-3">
            {(["all", "compliant", "non_compliant", "needs_review"] as const).map(
              (f) => (
                <button
                  key={f}
                  onClick={() => setFilter(f)}
                  className={cx(
                    "rounded-full px-3 py-1 text-xs font-semibold capitalize transition-colors",
                    filter === f
                      ? "bg-ink-900 text-white"
                      : "bg-ink-100 text-ink-500 hover:bg-ink-200",
                  )}
                >
                  {f.replace("_", " ")}
                </button>
              ),
            )}
          </div>
          {loading ? (
            <div className="space-y-3 p-4">
              {Array.from({ length: 4 }).map((_, i) => (
                <Skeleton key={i} className="h-16 w-full" />
              ))}
            </div>
          ) : filtered.length === 0 ? (
            <EmptyState
              icon={ICONS.reports}
              title="No reports"
              message="No inspection reports match this filter yet."
            />
          ) : (
            <ul className="max-h-[calc(100vh-16rem)] divide-y divide-ink-100 overflow-y-auto">
              {filtered.map((v) => (
                <li key={v.id}>
                  <button
                    onClick={() => setSelectedId(v.id)}
                    className={cx(
                      "flex w-full items-center gap-3 px-4 py-3.5 text-left transition-colors",
                      selectedId === v.id
                        ? "bg-brand-50/70"
                        : "hover:bg-ink-50",
                    )}
                  >
                    <ScoreRing score={v.score} size={42} stroke={4} />
                    <div className="min-w-0 flex-1">
                      <div className="truncate text-sm font-semibold text-ink-900">
                        {v.productName}
                      </div>
                      <div className="mt-0.5 text-xs text-ink-400">
                        {timeAgo(v.createdAt)} · {v.passed}P / {v.failed}F /{" "}
                        {v.warnings}W
                      </div>
                    </div>
                    <ResultBadge result={v.result} />
                  </button>
                </li>
              ))}
            </ul>
          )}
        </Card>

        {/* Detail */}
        <div className="lg:col-span-3">
          {!selectedId ? (
            <Card className="min-h-[400px]">
              <EmptyState
                icon={ICONS.reports}
                title="Select a report"
                message="Choose an inspection report from the list to see its rule-level findings and OCR evidence."
              />
            </Card>
          ) : detailLoading || !detail ? (
            <Card className="min-h-[400px] p-6">
              <Skeleton className="h-16 w-full" />
              <Skeleton className="mt-4 h-24 w-full" />
              <Skeleton className="mt-4 h-40 w-full" />
            </Card>
          ) : (
            <div className="space-y-4 animate-fade-up">
              <Card className="p-5">
                <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                  <div className="flex items-center gap-4">
                    <ScoreRing
                      score={detail.verification.score}
                      size={64}
                      stroke={6}
                    />
                    <div>
                      <div className="flex flex-wrap items-center gap-2">
                        <h3 className="text-lg font-bold text-ink-950">
                          {detail.verification.productName}
                        </h3>
                        <ResultBadge result={detail.verification.result} />
                      </div>
                      <div className="mt-1 text-xs text-ink-400">
                        Report {detail.verification.id.slice(0, 8)} ·{" "}
                        {formatDate(detail.verification.createdAt)}
                      </div>
                    </div>
                  </div>
                  <Button
                    variant="secondary"
                    onClick={() =>
                      download(
                        detail.verification,
                        detail.findings,
                      )
                    }
                  >
                    <Icon d={ICONS.download} className="h-4 w-4" />
                    Download
                  </Button>
                </div>
                <p className="mt-4 rounded-xl bg-ink-50 px-4 py-3 text-sm leading-relaxed text-ink-700">
                  {detail.verification.summary}
                </p>
              </Card>

              <Card>
                <div className="flex items-center justify-between border-b border-ink-100 px-5 py-3.5">
                  <h3 className="text-sm font-semibold text-ink-900">
                    Findings with evidence
                  </h3>
                  <div className="flex gap-1.5">
                    <Badge tone="emerald">
                      {detail.verification.passed} pass
                    </Badge>
                    <Badge tone="rose">
                      {detail.verification.failed} fail
                    </Badge>
                    <Badge tone="amber">
                      {detail.verification.warnings} warn
                    </Badge>
                  </div>
                </div>
                <ul className="divide-y divide-ink-100">
                  {detail.findings.map((f) => (
                    <li
                      key={f.id}
                      className={cx(
                        "px-5 py-4",
                        f.status === "not_applicable" && "bg-ink-50/50 opacity-60",
                      )}
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex items-center gap-2">
                          <span className="font-mono text-xs font-bold text-ink-400">
                            {f.code}
                          </span>
                          <span className="text-sm font-semibold text-ink-900">
                            {f.title}
                          </span>
                        </div>
                        <FindingStatusBadge status={f.status} />
                      </div>
                      <p className="mt-1.5 text-sm text-ink-600">{f.detail}</p>
                      {f.evidence && (
                        <div className="mt-2 rounded-lg border-l-2 border-brand-300 bg-brand-50/60 px-3 py-2">
                          <div className="text-[10px] font-bold uppercase tracking-wider text-brand-600">
                            OCR evidence
                          </div>
                          <p className="mt-0.5 font-mono text-xs text-ink-700">
                            {f.evidence}
                          </p>
                        </div>
                      )}
                      <div className="mt-2 flex flex-wrap items-center gap-2 text-[11px] text-ink-400">
                        <Badge tone="slate" className="!px-2 !py-0">
                          {SEVERITY_LABEL[f.severity]}
                        </Badge>
                        <span>{f.legalReference}</span>
                      </div>
                    </li>
                  ))}
                </ul>
              </Card>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
